### PR TITLE
Add # words, strokes, and detailed translation search

### PR DESCRIPTION
**Pull request by panathea**
### About
- # words and # strokes from Bozzy, re-added
- Filter strokes as "has a stroke starting with..." in its stroke list.
- Translation search supports case insensitive and regex flags and now searches in the translation instead of at the beginning.
### Reason

We are playing catchup with Bozzy features, while also adding the case-insensitive as an option and regex support which I've found myself wanting.

When the regex doesn't compile there's a handy little tooltip error.
### Tests

No tests written yet, considering pulling it out as a function for testing.

### CODE REVIEW

**Comment by panathea** [comment]
screen shot 2016-09-27 at 4 50 10 pm

**Comment by panathea** [comment]
Updated the description... I must have been tired when I wrote it the first time!

**Comment by panathea** [comment]
Updated with test cases.

**Comment by panathea** [comment]
...took a while, but the tests kept failing because I was introducing the need for QT to run the tests... instead I've moved my logic into `steno.py` and now hopefully it will continue to work. Also gives the benefit of allowing a filter in some other use for the future.

**Comment by iangermann** [comment]
Looks good! My only concern is that the regex and case sensitivity only apply to the translation filter, but that isn't very clear in the UI. I will merge it in because we will re-work the filtering interface soon anyway.

**Pull request merged**
