### PR TITLE
Add collisions and duplicates filtering

### LINKED ISSUE #9: 3: Add collisions only, and hide duplicates checkboxes for filter.

### PR DESCRIPTION
**Pull request by panathea**
### About

Add the ability to only include (collisions || duplicates) while searching.

Collisions: matching stroke but differing translation

Duplicates: matching stroke and translation

### Issues

Fixes #9

### Feedback

I'd like code and UI feedback if possible, @Germanika @sofa13 

The UI is a little messy and the code may be complex. I still need to fix testing to ensure the tests only get run in the right environment. I'm pushing it to start running CI.

### CODE REVIEW

**Comment by panathea** [comment]
The tests have been fixed -- please review the UI/code now :)

**Comment by panathea** [comment]
I've updated the commit with a modification of the UI to be a sidebar:

screen shot 2016-11-01 at 4 20 46 pm

**Comment by iangermann** [comment]
I'm glad I saw this, I was just in the middle of reworking the UI, thanks for including a screenshot!

**Comment by iangermann** [comment]
I checked out the change and the filter/clear buttons don't seem to be working. Maybe they're not connected to their functions properly anymore? Otherwise I quite like the UI.

**Comment by panathea** [comment]
Thanks for noticing, apparently I deleted the slots/signals. I also fixed the tabbing order.

**Pull request merged**
